# Generated by Django 4.1.6 on 2023-04-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ('-created',)},
        ),
    ]
