# Generated by Django 4.1.6 on 2023-02-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_contactus_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(max_length=25)),
                ('buy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sell', models.DecimalField(decimal_places=2, max_digits=6)),
                ('source', models.CharField(max_length=25)),
            ],
        ),
    ]
