# Generated by Django 4.1.6 on 2023-03-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(max_length=255),
        ),
    ]
